apiVersion: v1
kind: Pod
metadata:
  name: mysql-fiap
  namespace: rms
  labels:
    app: mysql-fiap
spec:
  containers:
    - name: mongo-fiap-container
      image: mongodb/mongodb-community-server:latest
      ports:
        - containerPort: 27017
      envFrom:
        - configMapRef:
            name: mysql-fiap-configmap
