apiVersion: v1
kind: Service
metadata:
  name: svc-db-payment
  namespace: rms
  labels:
    app: mysql-fiap
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30001
  selector:
    app: mysql-fiap
