apiVersion: v1
kind: Service
metadata:
  name: svc-node-fiap
  namespace: rms
  labels:
    app: node-fiap
spec:
  type: NodePort
  selector:
    app: node-fiap
  ports:
    - protocol: TCP
      port: 3000  
      nodePort: 30000  

  